#!/bin/sh

##hbase conf
## 先检查 global.conf
## 再检查此处 conf
#nodeList="mds1 node29 node30"

dirPath="/tmp/"
#hadoopPath="/loongoop/loongoop-1.0.6-v2.7.2/bin/hadoop"
#hbasePath="/loongoop/hbase-1.3.1/bin/hbase"

#hbasePathShell="${hbasePath} shell"

#leofsSitePath="$(dirname $hadoopPath)/../etc/hadoop/leofs-site.xml"

##LOG PATH
#LOG_HBASE=/tmp/lgp-hbase.log		#记录基本执行case,和结果
#LOG_HBASE_RUN=/tmp/lgp-hbase-run.detail.log		#记录运行时的日志，和判断信息
