#!/bin/sh
nodeList="mds1 node29 node30"

dirPath="/tmp/"
hadoopPath="/loongoop/loongoop-1.0.6-v2.7.2/bin/hadoop"
hbasePath="/loongoop/hbase-1.3.1/bin/hbase"

hbasePathShell="${hbasePath} shell"

leofsSitePath="$(dirname $hadoopPath)/../etc/hadoop/leofs-site.xml"
